services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root  # Définir le mot de passe root dans mon pdoModel
      MYSQL_DATABASE: php_mvc               # Créer une base de données
      MYSQL_USER: user                    # Créer un utilisateur régulier
      MYSQL_PASSWORD: user123            # Définir le mot de passe de l'utilisateur
    
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
      
  
  phpmyadmin-admin-db:
    container_name: container_phpmyadmin-admindb
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8085:80"
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: user123
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data: